name: Python Linter

on:
  push:
    paths:
      - '*.py'
  pull_request:
  workflow_dispatch:
jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 . --count --show-source --statistics --append-config Python/.flake8 
      - name: Test Insertion Sort
        run: python Python/sort_test/test_insertion_sort.py 

